### ISSUE TITLE
希望能支持将权限管理存储在sqlite中，目前使用内存存储容易丢失数据，经常需要重新创建用户，很不方便。

### ISSUE THREAD

**Issue by caopengfei** [wzxinchen/BlazAdmin#16]
如题。

**Comment by wzxinchen** [comment]
Demo 中放到内存只是为了方便测试和演示，BlazAdmin 本身并不管这一块，你可以在Startup中连接SQLite即可

**Comment by wzxinchen** [comment]
有问题可以再打开

**Comment by caopengfei** [comment]
我试过了，报错：
Error: System.InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Database.Transaction.AmbientTransactionWarning': An ambient transaction has been detected. The current provider does not support ambient transactions. See http://go.microsoft.com/fwlink/?LinkId=800142 This exception can be suppressed or logged by passing event ID 'RelationalEventId.AmbientTransactionWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.

**Comment by caopengfei** [comment]
另外我还试了sql express，也报错了：
blazor.server.js:15 [2019-12-25T02:37:24.983Z] Error: System.InvalidOperationException: A TransactionScope must be disposed on the same thread that it was created.
   at System.Transactions.TransactionScope.Dispose()
   at BlazAdmin.ServerRender.UserServiceBase`2.CreateSuperUserAsync(String username, String password)
   at BlazAdmin.BCreateSuperUserBase.CreateAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Blazui.Component.Button.BButtonBase.OnButtonClickedAsync(MouseEventArgs e)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by wzxinchen** [comment]
方便提供一下源码吗？

**Comment by caopengfei** [comment]
我试着在demo项目上测试吧

**Comment by wzxinchen** [comment]
我大概知道问题在哪了，我查查资料

**Comment by wzxinchen** [comment]
https://stackoverflow.com/questions/13543254/get-transactionscope-to-work-with-async-await
根本原因是 TransactionScope 这个类在异步环境下以前的写法不支持，这个问题我下个版本修复
